version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    image: asesorias_django
    container_name: asesorias_django
    command:
      - bash
      - -c
      - |
        python manage.py migrate
        python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - .:/code
    depends_on:
      - db
    env_file:
      - ./.envs/.django
      - ./.envs/.postgres

  db:
    build:
      context: .
      dockerfile: ./compose/postgres/Dockerfile
    image: asesorias_postgres
    container_name: asesorias_postgres
    env_file:
      - ./.envs/.postgres
    ports:
      - '4321:5432'
