# Generated by Django 3.2.20 on 2023-07-13 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfiles'},
        ),
        migrations.AlterField(
            model_name='perfil',
            name='zonas',
            field=models.ManyToManyField(related_name='perfiles', to='ventas.Zona'),
        ),
    ]
